config/routes.rb
BookManager3::Application.routes.draw do
 
  # Generated model routes
  resources :books
  # need routes for authors and categories ...
  resources :authors
  resources :categories
  
  # Additional routes we've created for this project
  get 'proposed' => 'books#proposed', as: :proposed_books
  get 'contracted' => 'books#contracted', as: :contracted_books
  
  # Set the root url
  root to: 'books#index', as: :home

end

app/models/author.rb
class Author < ActiveRecord::Base
  # Relationships
  has_many :book_authors
  has_many :books, through: :book_authors
  
  # Validations
  validates_presence_of :first_name, :last_name
  
  # Scopes
  scope :alphabetical, -> { order('last_name, first_name') }
  scope :active, -> { where(active: true) }
  
  # Methods
  def name
    "#{last_name}, #{first_name}"
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
  # Relationships
  belongs_to :category
  has_many :book_authors
  has_many :authors, through: :book_authors
  
  
  # Validations built into rails
  validates :title, presence: true
  validates :units_sold, numericality: {only_integer: true, greater_than_or_equal_to: 0}
  
  # Date validations using validates_timeliness gem
  # see https://github.com/adzap/validates_timeliness for documentation
  validates_date :proposal_date, on_or_before: -> { Date.current }
  validates_date :contract_date, after: :proposal_date, on_or_before: -> { Date.current }, allow_blank: true
  validates_date :published_date, after: :contract_date, on_or_before: -> { Date.current }, allow_blank: true  
  
  # Custom validation
  validate :category_is_active_in_system
  
  
  # Scopes
  scope :by_title, -> { order('title') }
  scope :by_category, -> { joins(:category).order('categories.name, books.title') }
  
  scope :published, -> { where('published_date IS NOT NULL') }
  scope :under_contract, -> { where('contract_date IS NOT NULL AND published_date IS NULL') }
  scope :proposed, -> { where('proposal_date IS NOT NULL AND contract_date IS NULL') }
  
  scope :for_category, ->(category_id) { where("category_id = ?", category_id) }
  
  # Other methods
  private
  def category_is_active_in_system
    active_categories = Category.active.all.map{|c| c.id}
    unless active_categories.include?(self.category_id)
      errors.add(:category, "is not currently active in BookManager")
    end
  end
end

app/models/book_author.rb
class BookAuthor < ActiveRecord::Base
  belongs_to :book
  belongs_to :author
end

app/models/category.rb
class Category < ActiveRecord::Base
  # Relationships
  has_many :books
  
  # Validations
  validates :name, presence: true
  
  # Scopes
  scope :alphabetical, -> { order('name') }
  scope :active, -> { where(active: true) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  def set_author
    @author = Author.find(params[:id])
  end

  def index
  	@authors = Author.active.alphabetical.paginate(:page => params[:page]).per_page(10)
  end

  def show

  end

  def edit

  end

  def new 
  	@author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      redirect_to author_path(@author), notice: "#{@author.name} was added to the system."
    else
      render action: 'new'
    end
  end

  def update
    if @author.update(author_params)
      redirect_to author_path(@author), notice: "#{@author.name} was revised in the system."
    else
      render action: 'edit'
    end
  end

  def destroy
    @author.destroy
    redirect_to authors_url
  end

  private

  def author_params
    params.require(:author).permit(:first_name, :last_name, :active)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # show, edit, update and destroy all need a common @book object to work with, so find it first...
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # instead of all books, we are only getting a list of published books
  def index
    @books = Book.published.by_title.paginate(:page => params[:page]).per_page(10)
  end
  
  # this is special action we've created to give us list of proposed books
  def proposed
    @books = Book.proposed.by_category.paginate(:page => params[:page]).per_page(10)
  end
  
  # this is special action we've created to give us list of books under contract
  def contracted
    @books = Book.under_contract.by_category.paginate(:page => params[:page]).per_page(10)
  end

  def show
  end

  def new
    @book = Book.new
  end

  def edit
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to @book, notice: "#{@book.title} was added to the system."
    else
      render action: 'new'
    end
  end

  def update
    if @book.update(book_params)
      redirect_to @book, notice: "#{@book.title} was revised in the system."
    else
      render action: 'edit'
    end
  end

  def destroy
    @book.destroy
    redirect_to books_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from users (potential hackers), but rather only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :category_id, :units_sold, :proposal_date, :contract_date, :published_date, :notes, :author_ids => [])
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def set_category
    @category = category.find(params[:id])
  end

  def index
  	@categories = Category.active.alphabetical.paginate(:page => params[:page]).per_page(10)
  end

  def show

  end

  def edit

  end

  def new 
  	@category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to category_path(@category), notice: "#{@category.name} was added to the system."
    else
      render action: 'new'
    end
  end

  def update
    if @category.update(category_params)
      redirect_to category_path(@category), notice: "#{@category.name} was revised in the system."
    else
      render action: 'edit'
    end
  end

  def destroy
    @category.destroy
    redirect_to categorys_url
  end

  private

  def category_params
    params.require(:category).permit(:first_name, :last_name, :active)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h3>

      <ul>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/_list_of_books.html.erb
<p>
	<b><%= pluralize(@author.books.size, 'Book') %></b><br />
	<ul>
		<% for book in @author.books %>
			<li><%= link_to((book.title), book_path(book)) %></li>
		<% end  %>
	</ul>
</p>

app/views/authors/edit.html.erb
<h3>Editing author</h3>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h3>Listing Active Authors</h3>

<table>
  <tr>
    <th>Author Name</th>
    <th></th>
    <th></th>
  </tr>

<% @authors.each do |author| %>
  <tr>
    <td><%= link_to author.name, author_path(author) %></td>
    <td><%= link_to 'Edit', edit_author_path(author) %></td>
    <td><%= link_to 'Destroy', author, data: { confirm: 'Are you sure?' }, method: :delete %></td>
  </tr>
<% end %>
</table>
<br />
<!-- Add the pagination using will_paginate gem -->
<span class="paginate">
<%= will_paginate @authors, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next" %>
</span>

<br />

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h3>New author</h3>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @author.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @author.last_name %>
</p>

<%= render :partial => "list_of_books" %>


<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/books/_authors_checkboxes.html.erb
  <div>
      <% for author in Author.active.alphabetical %>
          <%= check_box_tag "book[author_ids][]", author.id, @book.authors.include?(author), {id: author.id} %>
          <label for="<%= author.id %>"><%= author.name %></label>
          <br />
      <% end  %>
  </div>

app/views/books/_form.html.erb
<%= simple_form_for(@book, html: { class: 'form-horizontal' }) do |f| %>
	
  
  <%= simple_form_for @book, html: { class: 'form-horizontal' } do |f| %>
    <fieldset>
      <legend><%= controller.action_name.capitalize %> Book
	  </legend>

	    <%= f.input :title %>
	    <%= f.association :category %>
	<div class="row">
      <div class="col s4">
    <%= f.input :proposal_date, as: :date, order: [:month, :day, :year], start_year: Date.today.year - 2, end_year: Date.today.year %>

      </div>
      <div class="col s4">
    <%= f.input :contract_date, as: :date, order: [:month, :day, :year], include_blank: true, start_year: Date.today.year - 2, end_year: Date.today.year %>
      </div>
      <div class="col s4">
    <%= f.input :published_date, as: :date, order: [:month, :day, :year], include_blank: true, start_year: Date.today.year - 2, end_year: Date.today.year%>
      </div>
  </div>
  <%= f.input :notes, input_html: { class: 'materialize-textarea' } %>
  <%= render "authors_checkboxes" %>
    <div class="form-actions">
    <%= f.submit nil, class: 'btn' %>
    <%= link_to 'Cancel', books_path, :class => 'btn deep-orange lighten-3' %>
  </div>

    </fieldset>
  <% end %>

<% end %>

app/views/books/_list_of_authors.html.erb
<p>
	<b><%= pluralize(@book.authors.size, 'Author') %></b><br />
	<ul>
		<% for author in @book.authors.alphabetical %>
			<li><%= link_to((author.name), author_path(author)) %></li>
		<% end  %>
	</ul>
</p>

app/views/books/contracted.html.erb
<h3>Books Currently Under Contract</h3>

<table>
  <tr>
    <th>Title</th>
    <th>Category</th>
		<th>Contract Date</th>
		<th>Author (first)</th>
    <th></th>
    <th></th>
  </tr>

<% @books.each do |book| %>
  <tr>
    <td><%= link_to book.title, book_path(book) %></td>
    <td><%= book.category.name %></td>
		<td><%= book.contract_date.strftime("%m/%d/%y") %></td>
		<td><%= book.authors.alphabetical.first.name %></td>
    <td><%= link_to 'Edit', edit_book_path(book) %></td>
    <td><%= link_to 'Destroy', book, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>
<br />
<!-- Add the pagination using will_paginate gem -->
<span class="paginate">
<%= will_paginate @books, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next" %>
</span>

<br />

<ul class="options">Switch to:
	<li><%= link_to 'Published Books', books_path %></li>
	<li><%= link_to 'Proposed Books', proposed_books_path %></li>
	<li><%= link_to 'Add a New Book', new_book_path %></li>
</ul>

app/views/books/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h3>Listing Published Books</h3>

<table class="striped">
  <tr>
    <th>Title</th>
    <th>Category</th>
		<th>Year</th>
		<th>Author (first)</th>
		<th>Units Sold</th>
    <th></th>
    <th></th>
  </tr>

<% @books.each do |book| %>
  <tr>
    <td><%= link_to book.title, book_path(book) %></td>
    <td><%= book.category.name %></td>
		<td><%= book.published_date.year %></td>
		<td><%= book.authors.alphabetical.first.name %></td>
		<td align="right"><%= number_with_delimiter(book.units_sold) %></td>
    <td><%= link_to 'Edit', edit_book_path(book), class: "btn waves-effect waves-light blue" %></td>
    <td><%= link_to 'Destroy', book, confirm: 'Are you sure?', class: "btn waves-effect waves-light red", method: :delete %></td>
  </tr>
<% end %>
</table>
<br />
<!-- Add the pagination using will_paginate gem -->
<span class="paginate">
<%= will_paginate @books, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next" %>
</span>

<br />

<ul class="options">Switch to:
	<li><%= link_to 'Books Under Contract', contracted_books_path %></li>
	<li><%= link_to 'Proposed Books', proposed_books_path %></li>
	<li><%= link_to 'Add a New Book', new_book_path %></li>
</ul>

app/views/books/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/proposed.html.erb
<h3>Listing Proposed Books</h3>

<table>
  <tr>
    <th>Title</th>
    <th>Category</th>
		<th>Proposal Date</th>
		<th>Author (first)</th>
    <th></th>
    <th></th>
  </tr>

<% @books.each do |book| %>
  <tr>
    <td><%= link_to book.title, book_path(book) %></td>
    <td><%= book.category.name %></td>
		<td><%= book.proposal_date.strftime("%m/%d/%y") %></td>
		<td><%= book.authors.alphabetical.first.name %></td>
    <td><%= link_to 'Edit', edit_book_path(book) %></td>
    <td><%= link_to 'Destroy', book, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>
<br />
<!-- Add the pagination using will_paginate gem -->
<span class="paginate">
<%= will_paginate @books, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next" %>
</span>

<br />

<ul class="options">Switch to:
	<li><%= link_to 'Published Books', books_path %></li>
	<li><%= link_to 'Books Under Contract', contracted_books_path %></li>
	<li><%= link_to 'Add a New Book', new_book_path %></li>
</ul>

app/views/books/show.html.erb
<p>
  <b>Title:</b>
  <%= @book.title %>
</p>

<p>
  <b>Category:</b>
  <%= @book.category.name %>
</p>

<%= render 'list_of_authors' %>

<p>
  <b>Proposal date:</b>
  <%= @book.proposal_date.strftime("%m/%d/%y") %>
</p>

<p>
  <b>Contract date:</b>
  <%= @book.contract_date.strftime("%m/%d/%y") unless @book.contract_date.nil? %>
</p>

<p>
  <b>Published date:</b>
  <%= @book.published_date.strftime("%m/%d/%y") unless @book.published_date.nil? %>
</p> 

<p>
  <b>Units Sold:</b>
  <%= number_with_delimiter @book.units_sold %>
</p>

<p>
  <b>Notes:</b><br />
  <%= @book.notes %>
</p>


<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h3>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h3>Editing category</h3>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h3>Listing categories</h3>

<table>
  <tr>
    <th>Name</th>
    <th>Active</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= category.active %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h3>New category</h3>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>

<p>
  <b>Active:</b>
  <%= @category.active %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>BookManager :: <%= controller.controller_name.capitalize %> - <%= controller.action_name.capitalize %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
  <body>
    <nav>
    <div class="nav-wrapper container">
      <%= link_to "BookManager", home_path,
            { :class=> "brand-logo left" } %>
      <ul class="right">
        <li><%= link_to "Categories", categories_path %></li>
        <li><a class="dropdown-button" href="#!" data-activates="dropdown1">Authors<i class="mdi-navigation-arrow-drop-down right"></i></a></li>
        <ul id="dropdown1" class="dropdown-content">
          <li><%= link_to "List Authors", authors_path %></li>
          <li><%= link_to "Add an Author", new_author_path %></li>
        </ul>
      </ul>
    </div>
  </nav>
    <div class="container">
      <div class="row">
        <div class="col s8">
          <% flash.each do |name, msg| %>
    <div class="alert-box <%= name == :notice ? "success" : "warning" %> radius">
      <a href="#" class="close">&times;</a>
      <%= msg %>
    </div>
  <% end %>
          <!-- MAIN CONTENT GOES HERE -->
          <%= yield %>
          <%= javascript_include_tag "application" %>
        </div>

        <br><br><br>

        <div class="col s3 offset-s1 card">
          <!-- SIDEBAR CONTENT GOES HERE -->
          <%= render partial: 'partials/quick_links' %>
        </div>
      </div>
    </div>

    <footer class="container">
      <div class="row">
        <div class="col s12 center">
          <%= render partial: 'partials/footer' %>
        </div>
      </div> 
    </footer>     
  </body>
</html>

app/views/partials/_footer.html.erb
<p>
  <a href="#">Home</a>&nbsp;&nbsp;::&nbsp;&nbsp;
  <a href="#">About Us</a>&nbsp;&nbsp;::&nbsp;&nbsp;
  <a href="#">Contact Us</a>&nbsp;&nbsp;::&nbsp;&nbsp;
  <a href="#">Back to top</a>
</p>
<div id="copyright">
  <br />Webmaster: <%= mail_to "YOUR EMAIL", "YOUR NAME", :encode => "javascript" %>
    &nbsp;&nbsp;Copyright 2014
  <br /><br />
</div>

app/views/partials/_quick_links.html.erb
<h3>&nbsp;</h3>
<div class="panel clearfix">
  <h3>Quick Links</h3>
  <ul class="side-nav">Switch to:
    <li><%= link_to 'Published Books', books_path %></li>
    <li><%= link_to 'Under Contract', contracted_books_path %></li>
    <li><%= link_to 'New Proposals', proposed_books_path %></li>
    <li><%= link_to 'Add a New Book', new_book_path %></li>
  </ul>
</div>